window.TORONTO_REC_GENERATED = {
  "updated": "2026-09-02",
  "sessions": [
    {
      "id": "city-eastbayfront-2026-09-08-1330-badminton",
      "centre": "eastbayfront",
      "date": "2026-09-08",
      "name": "Badminton",
      "age": "adult",
      "day": "tuesday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-08-1715-pickleball",
      "centre": "yonge",
      "date": "2026-09-08",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-08-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-08",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-08-1930-pickleball",
      "centre": "yonge",
      "date": "2026-09-08",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-08-1200-pickleball",
      "centre": "yonge",
      "date": "2026-09-08",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-09-1830-volleyball",
      "centre": "stlawrence",
      "date": "2026-09-09",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-09-0700-badminton",
      "centre": "yonge",
      "date": "2026-09-09",
      "name": "Badminton",
      "age": "adult",
      "day": "wednesday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-09-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-09",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-09-1200-volleyball",
      "centre": "yonge",
      "date": "2026-09-09",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-10-1400-badminton-women",
      "centre": "eastbayfront",
      "date": "2026-09-10",
      "name": "Badminton (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "02:00 PM - 04:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-10-1715-volleyball",
      "centre": "yonge",
      "date": "2026-09-10",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-10-1830-badminton",
      "centre": "stlawrence",
      "date": "2026-09-10",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-10-0700-badminton",
      "centre": "yonge",
      "date": "2026-09-10",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-10-1930-volleyball",
      "centre": "yonge",
      "date": "2026-09-10",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-10-0915-pickleball-women",
      "centre": "eastbayfront",
      "date": "2026-09-10",
      "name": "Pickleball (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-10-0930-badminton",
      "centre": "yonge",
      "date": "2026-09-10",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-10-1200-badminton",
      "centre": "yonge",
      "date": "2026-09-10",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-11-1415-volleyball",
      "centre": "eastbayfront",
      "date": "2026-09-11",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "02:15 PM - 04:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-11-1845-volleyball",
      "centre": "eastbayfront",
      "date": "2026-09-11",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "06:45 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-11-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-11",
      "name": "Pickleball",
      "age": "adult",
      "day": "friday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-11-1930-badminton",
      "centre": "yonge",
      "date": "2026-09-11",
      "name": "Badminton",
      "age": "adult",
      "day": "friday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-11-1200-pickleball",
      "centre": "yonge",
      "date": "2026-09-11",
      "name": "Pickleball",
      "age": "adult",
      "day": "friday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-12-1315-badminton",
      "centre": "johninnes",
      "date": "2026-09-12",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "01:15 PM - 04:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-12-1430-pickleball",
      "centre": "stlawrence",
      "date": "2026-09-12",
      "name": "Pickleball",
      "age": "adult",
      "day": "saturday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-12-1730-volleyball",
      "centre": "yonge",
      "date": "2026-09-12",
      "name": "Volleyball",
      "age": "adult",
      "day": "saturday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-12-1100-badminton",
      "centre": "stlawrence",
      "date": "2026-09-12",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "11:00 AM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-13-1330-pickleball",
      "centre": "yonge",
      "date": "2026-09-13",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-13-1430-pickleball",
      "centre": "johninnes",
      "date": "2026-09-13",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-13-1600-badminton",
      "centre": "stlawrence",
      "date": "2026-09-13",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "04:00 PM - 07:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-13-1730-badminton",
      "centre": "yonge",
      "date": "2026-09-13",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-13-1745-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-13",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "05:45 PM - 07:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-13-1230-volleyball",
      "centre": "stlawrence",
      "date": "2026-09-13",
      "name": "Volleyball",
      "age": "adult",
      "day": "sunday",
      "time": "12:30 PM - 03:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-14-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-14",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-14-2000-badminton",
      "centre": "johninnes",
      "date": "2026-09-14",
      "name": "Badminton",
      "age": "adult",
      "day": "monday",
      "time": "08:00 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-14-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-14",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-14-0930-pickleball",
      "centre": "johninnes",
      "date": "2026-09-14",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-14-1145-pickleball",
      "centre": "johninnes",
      "date": "2026-09-14",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "11:45 AM - 01:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-15-1330-badminton",
      "centre": "eastbayfront",
      "date": "2026-09-15",
      "name": "Badminton",
      "age": "adult",
      "day": "tuesday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-15-1715-pickleball",
      "centre": "yonge",
      "date": "2026-09-15",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-15-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-15",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-15-1930-pickleball",
      "centre": "yonge",
      "date": "2026-09-15",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-15-1200-pickleball",
      "centre": "yonge",
      "date": "2026-09-15",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-16-1830-volleyball",
      "centre": "stlawrence",
      "date": "2026-09-16",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-16-0700-badminton",
      "centre": "yonge",
      "date": "2026-09-16",
      "name": "Badminton",
      "age": "adult",
      "day": "wednesday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-16-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-16",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-16-1200-volleyball",
      "centre": "yonge",
      "date": "2026-09-16",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-17-1400-badminton-women",
      "centre": "eastbayfront",
      "date": "2026-09-17",
      "name": "Badminton (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "02:00 PM - 04:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-17-1715-volleyball",
      "centre": "yonge",
      "date": "2026-09-17",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-17-1830-badminton",
      "centre": "stlawrence",
      "date": "2026-09-17",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-17-0700-badminton",
      "centre": "yonge",
      "date": "2026-09-17",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-17-1930-volleyball",
      "centre": "yonge",
      "date": "2026-09-17",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-17-0915-pickleball-women",
      "centre": "eastbayfront",
      "date": "2026-09-17",
      "name": "Pickleball (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-17-0930-badminton",
      "centre": "yonge",
      "date": "2026-09-17",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-17-1200-badminton",
      "centre": "yonge",
      "date": "2026-09-17",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-18-1415-volleyball",
      "centre": "eastbayfront",
      "date": "2026-09-18",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "02:15 PM - 04:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-18-1845-volleyball",
      "centre": "eastbayfront",
      "date": "2026-09-18",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "06:45 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-18-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-18",
      "name": "Pickleball",
      "age": "adult",
      "day": "friday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-18-1930-badminton",
      "centre": "yonge",
      "date": "2026-09-18",
      "name": "Badminton",
      "age": "adult",
      "day": "friday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-18-1200-pickleball",
      "centre": "yonge",
      "date": "2026-09-18",
      "name": "Pickleball",
      "age": "adult",
      "day": "friday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-19-1315-badminton",
      "centre": "johninnes",
      "date": "2026-09-19",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "01:15 PM - 04:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-19-1430-pickleball",
      "centre": "stlawrence",
      "date": "2026-09-19",
      "name": "Pickleball",
      "age": "adult",
      "day": "saturday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-19-1730-volleyball",
      "centre": "yonge",
      "date": "2026-09-19",
      "name": "Volleyball",
      "age": "adult",
      "day": "saturday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-19-1100-badminton",
      "centre": "stlawrence",
      "date": "2026-09-19",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "11:00 AM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-20-1330-pickleball",
      "centre": "yonge",
      "date": "2026-09-20",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-20-1430-pickleball",
      "centre": "johninnes",
      "date": "2026-09-20",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-20-1600-badminton",
      "centre": "stlawrence",
      "date": "2026-09-20",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "04:00 PM - 07:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-20-1730-badminton",
      "centre": "yonge",
      "date": "2026-09-20",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-20-1745-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-20",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "05:45 PM - 07:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-20-1130-badminton",
      "centre": "eastbayfront",
      "date": "2026-09-20",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "11:30 AM - 01:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-20-1230-volleyball",
      "centre": "stlawrence",
      "date": "2026-09-20",
      "name": "Volleyball",
      "age": "adult",
      "day": "sunday",
      "time": "12:30 PM - 03:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-21-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-21",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-21-2000-badminton",
      "centre": "johninnes",
      "date": "2026-09-21",
      "name": "Badminton",
      "age": "adult",
      "day": "monday",
      "time": "08:00 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-21-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-21",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-21-0930-pickleball",
      "centre": "johninnes",
      "date": "2026-09-21",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-21-1145-pickleball",
      "centre": "johninnes",
      "date": "2026-09-21",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "11:45 AM - 01:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-22-1330-badminton",
      "centre": "eastbayfront",
      "date": "2026-09-22",
      "name": "Badminton",
      "age": "adult",
      "day": "tuesday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-22-1715-pickleball",
      "centre": "yonge",
      "date": "2026-09-22",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-22-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-22",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-22-1930-pickleball",
      "centre": "yonge",
      "date": "2026-09-22",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-22-1200-pickleball",
      "centre": "yonge",
      "date": "2026-09-22",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-23-1830-volleyball",
      "centre": "stlawrence",
      "date": "2026-09-23",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-23-0700-badminton",
      "centre": "yonge",
      "date": "2026-09-23",
      "name": "Badminton",
      "age": "adult",
      "day": "wednesday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-23-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-23",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-23-1200-volleyball",
      "centre": "yonge",
      "date": "2026-09-23",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-24-1400-badminton-women",
      "centre": "eastbayfront",
      "date": "2026-09-24",
      "name": "Badminton (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "02:00 PM - 04:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-24-1715-volleyball",
      "centre": "yonge",
      "date": "2026-09-24",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-24-1830-badminton",
      "centre": "stlawrence",
      "date": "2026-09-24",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-24-0700-badminton",
      "centre": "yonge",
      "date": "2026-09-24",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-24-1930-volleyball",
      "centre": "yonge",
      "date": "2026-09-24",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-24-0915-pickleball-women",
      "centre": "eastbayfront",
      "date": "2026-09-24",
      "name": "Pickleball (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-25-1415-volleyball",
      "centre": "eastbayfront",
      "date": "2026-09-25",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "02:15 PM - 04:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-25-1845-volleyball",
      "centre": "eastbayfront",
      "date": "2026-09-25",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "06:45 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-25-0700-pickleball",
      "centre": "yonge",
      "date": "2026-09-25",
      "name": "Pickleball",
      "age": "adult",
      "day": "friday",
      "time": "07:00 AM - 09:00 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-25-1930-badminton",
      "centre": "yonge",
      "date": "2026-09-25",
      "name": "Badminton",
      "age": "adult",
      "day": "friday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-26-1315-badminton",
      "centre": "johninnes",
      "date": "2026-09-26",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "01:15 PM - 04:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-26-1430-pickleball",
      "centre": "stlawrence",
      "date": "2026-09-26",
      "name": "Pickleball",
      "age": "adult",
      "day": "saturday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-26-1730-volleyball",
      "centre": "yonge",
      "date": "2026-09-26",
      "name": "Volleyball",
      "age": "adult",
      "day": "saturday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-26-1100-badminton",
      "centre": "stlawrence",
      "date": "2026-09-26",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "11:00 AM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-27-1330-pickleball",
      "centre": "yonge",
      "date": "2026-09-27",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-27-1430-pickleball",
      "centre": "johninnes",
      "date": "2026-09-27",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-27-1600-badminton",
      "centre": "stlawrence",
      "date": "2026-09-27",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "04:00 PM - 07:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-27-1730-badminton",
      "centre": "yonge",
      "date": "2026-09-27",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-27-1745-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-27",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "05:45 PM - 07:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-27-1130-badminton",
      "centre": "eastbayfront",
      "date": "2026-09-27",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "11:30 AM - 01:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-27-1230-volleyball",
      "centre": "stlawrence",
      "date": "2026-09-27",
      "name": "Volleyball",
      "age": "adult",
      "day": "sunday",
      "time": "12:30 PM - 03:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-28-2000-badminton",
      "centre": "johninnes",
      "date": "2026-09-28",
      "name": "Badminton",
      "age": "adult",
      "day": "monday",
      "time": "08:00 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-28-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-28",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-28-0930-pickleball",
      "centre": "johninnes",
      "date": "2026-09-28",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-09-28-1145-pickleball",
      "centre": "johninnes",
      "date": "2026-09-28",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "11:45 AM - 01:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-29-1330-badminton",
      "centre": "eastbayfront",
      "date": "2026-09-29",
      "name": "Badminton",
      "age": "adult",
      "day": "tuesday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-29-1715-pickleball",
      "centre": "yonge",
      "date": "2026-09-29",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-29-1930-pickleball",
      "centre": "yonge",
      "date": "2026-09-29",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-09-29-2000-pickleball",
      "centre": "canoe",
      "date": "2026-09-29",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "08:00 PM - 10:00 PM",
      "access": "both",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-09-29-2000-volleyball",
      "centre": "canoe",
      "date": "2026-09-29",
      "name": "Volleyball",
      "age": "adult",
      "day": "tuesday",
      "time": "08:00 PM - 10:00 PM",
      "access": "both",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-29-1200-pickleball",
      "centre": "yonge",
      "date": "2026-09-29",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-09-30-1800-pickleball",
      "centre": "canoe",
      "date": "2026-09-30",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "06:00 PM - 08:00 PM",
      "access": "both",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-09-30-1830-volleyball",
      "centre": "stlawrence",
      "date": "2026-09-30",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-09-30-2000-pickleball",
      "centre": "canoe",
      "date": "2026-09-30",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "08:00 PM - 10:00 PM",
      "access": "both",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-09-30-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-09-30",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-09-30-1200-volleyball",
      "centre": "yonge",
      "date": "2026-09-30",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-01-1400-badminton-women",
      "centre": "eastbayfront",
      "date": "2026-10-01",
      "name": "Badminton (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "02:00 PM - 04:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-01-1715-volleyball",
      "centre": "yonge",
      "date": "2026-10-01",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-10-01-1830-badminton",
      "centre": "stlawrence",
      "date": "2026-10-01",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "06:30 PM - 08:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-01-1900-badminton",
      "centre": "canoe",
      "date": "2026-10-01",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "07:00 PM - 08:30 PM",
      "access": "both",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-01-1930-volleyball",
      "centre": "yonge",
      "date": "2026-10-01",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-01-2030-badminton",
      "centre": "canoe",
      "date": "2026-10-01",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "08:30 PM - 10:00 PM",
      "access": "both",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-01-0915-pickleball-women",
      "centre": "eastbayfront",
      "date": "2026-10-01",
      "name": "Pickleball (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-01-0930-badminton",
      "centre": "yonge",
      "date": "2026-10-01",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-01-1200-badminton",
      "centre": "yonge",
      "date": "2026-10-01",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-02-1415-volleyball",
      "centre": "eastbayfront",
      "date": "2026-10-02",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "02:15 PM - 04:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-02-1845-volleyball",
      "centre": "eastbayfront",
      "date": "2026-10-02",
      "name": "Volleyball",
      "age": "adult",
      "day": "friday",
      "time": "06:45 PM - 08:45 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-02-1930-badminton",
      "centre": "yonge",
      "date": "2026-10-02",
      "name": "Badminton",
      "age": "adult",
      "day": "friday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-02-1200-pickleball",
      "centre": "yonge",
      "date": "2026-10-02",
      "name": "Pickleball",
      "age": "adult",
      "day": "friday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-10-03-1315-badminton",
      "centre": "johninnes",
      "date": "2026-10-03",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "01:15 PM - 04:45 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-10-03-1430-pickleball",
      "centre": "stlawrence",
      "date": "2026-10-03",
      "name": "Pickleball",
      "age": "adult",
      "day": "saturday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-03-1730-volleyball",
      "centre": "yonge",
      "date": "2026-10-03",
      "name": "Volleyball",
      "age": "adult",
      "day": "saturday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-stlawrence-2026-10-03-1100-badminton",
      "centre": "stlawrence",
      "date": "2026-10-03",
      "name": "Badminton",
      "age": "adult",
      "day": "saturday",
      "time": "11:00 AM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-04-1300-badminton",
      "centre": "canoe",
      "date": "2026-10-04",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "01:00 PM - 02:30 PM",
      "access": "both",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-04-1330-pickleball",
      "centre": "yonge",
      "date": "2026-10-04",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-10-04-1430-pickleball",
      "centre": "johninnes",
      "date": "2026-10-04",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "02:30 PM - 04:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-04-1530-volleyball",
      "centre": "canoe",
      "date": "2026-10-04",
      "name": "Volleyball",
      "age": "adult",
      "day": "sunday",
      "time": "03:30 PM - 05:30 PM",
      "access": "both",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-04-1730-badminton",
      "centre": "yonge",
      "date": "2026-10-04",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "05:30 PM - 07:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-04-1745-pickleball",
      "centre": "eastbayfront",
      "date": "2026-10-04",
      "name": "Pickleball",
      "age": "adult",
      "day": "sunday",
      "time": "05:45 PM - 07:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-04-1130-badminton",
      "centre": "eastbayfront",
      "date": "2026-10-04",
      "name": "Badminton",
      "age": "adult",
      "day": "sunday",
      "time": "11:30 AM - 01:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-10-05-2000-badminton",
      "centre": "johninnes",
      "date": "2026-10-05",
      "name": "Badminton",
      "age": "adult",
      "day": "monday",
      "time": "08:00 PM - 09:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-05-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-10-05",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-10-05-0930-pickleball",
      "centre": "johninnes",
      "date": "2026-10-05",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-johninnes-2026-10-05-1145-pickleball",
      "centre": "johninnes",
      "date": "2026-10-05",
      "name": "Pickleball",
      "age": "adult",
      "day": "monday",
      "time": "11:45 AM - 01:45 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-06-1330-badminton",
      "centre": "eastbayfront",
      "date": "2026-10-06",
      "name": "Badminton",
      "age": "adult",
      "day": "tuesday",
      "time": "01:30 PM - 03:30 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-06-1715-pickleball",
      "centre": "yonge",
      "date": "2026-10-06",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-06-1930-pickleball",
      "centre": "yonge",
      "date": "2026-10-06",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-06-2000-pickleball",
      "centre": "canoe",
      "date": "2026-10-06",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "08:00 PM - 10:00 PM",
      "access": "both",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-06-2000-volleyball",
      "centre": "canoe",
      "date": "2026-10-06",
      "name": "Volleyball",
      "age": "adult",
      "day": "tuesday",
      "time": "08:00 PM - 10:00 PM",
      "access": "both",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-06-1200-pickleball",
      "centre": "yonge",
      "date": "2026-10-06",
      "name": "Pickleball",
      "age": "adult",
      "day": "tuesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-07-1800-pickleball",
      "centre": "canoe",
      "date": "2026-10-07",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "06:00 PM - 08:00 PM",
      "access": "both",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-07-2000-pickleball",
      "centre": "canoe",
      "date": "2026-10-07",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "08:00 PM - 10:00 PM",
      "access": "both",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-07-0915-pickleball",
      "centre": "eastbayfront",
      "date": "2026-10-07",
      "name": "Pickleball",
      "age": "adult",
      "day": "wednesday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-07-1200-volleyball",
      "centre": "yonge",
      "date": "2026-10-07",
      "name": "Volleyball",
      "age": "adult",
      "day": "wednesday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-08-1400-badminton-women",
      "centre": "eastbayfront",
      "date": "2026-10-08",
      "name": "Badminton (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "02:00 PM - 04:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-08-1715-volleyball",
      "centre": "yonge",
      "date": "2026-10-08",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "05:15 PM - 07:15 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-08-1900-badminton",
      "centre": "canoe",
      "date": "2026-10-08",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "07:00 PM - 08:30 PM",
      "access": "both",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-08-1930-volleyball",
      "centre": "yonge",
      "date": "2026-10-08",
      "name": "Volleyball",
      "age": "adult",
      "day": "thursday",
      "time": "07:30 PM - 09:30 PM",
      "access": "dropin",
      "sport": "volleyball",
      "status": "active"
    },
    {
      "id": "city-canoe-2026-10-08-2030-badminton",
      "centre": "canoe",
      "date": "2026-10-08",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "08:30 PM - 10:00 PM",
      "access": "both",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-eastbayfront-2026-10-08-0915-pickleball-women",
      "centre": "eastbayfront",
      "date": "2026-10-08",
      "name": "Pickleball (Women)",
      "age": "adult",
      "day": "thursday",
      "time": "09:15 AM - 11:15 AM",
      "access": "dropin",
      "sport": "pickleball",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-08-0930-badminton",
      "centre": "yonge",
      "date": "2026-10-08",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "09:30 AM - 11:30 AM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    },
    {
      "id": "city-yonge-2026-10-08-1200-badminton",
      "centre": "yonge",
      "date": "2026-10-08",
      "name": "Badminton",
      "age": "adult",
      "day": "thursday",
      "time": "12:00 PM - 02:00 PM",
      "access": "dropin",
      "sport": "badminton",
      "status": "active"
    }
  ]
};
